# src/api/v1/routes/reports.py
"""
Daily return API (EXPERIMENTAL — not a compliance product).

Serves rows of gold_cbn_daily_returns, generated by
src/flows/daily_report_flow.py. See src/engine/cbn_report.py for scope.

References:
    - API Specification §5: Reports
"""

from datetime import date
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy import text

from src.api.middleware.auth import require_role
from src.api.v1.routes.reconciliation import READ_ROLES, money
from src.storage.postgres import readonly_session

router = APIRouter(prefix="/v1/reports", tags=["Daily returns (experimental)"])

_SELECT = """
    SELECT return_date, total_transaction_count, total_credit_volume_ngn, total_debit_volume_ngn,
           match_rate_pct, cross_border_count, suspicious_tx_count, open_discrepancy_count,
           unreconciled_exposure_ngn, submission_status::text AS submission_status, generated_at
    FROM gold_cbn_daily_returns
"""


def _serialise(r: Any) -> dict[str, Any]:
    return {
        "report_date": r["return_date"].isoformat(),
        "total_transactions": r["total_transaction_count"],
        "total_volume_ngn": money(r["total_credit_volume_ngn"] + r["total_debit_volume_ngn"]),
        "match_rate_pct": str(r["match_rate_pct"]) if r["match_rate_pct"] is not None else None,
        "cross_border_count": r["cross_border_count"],
        "suspicious_flags": r["suspicious_tx_count"],
        "open_discrepancies": r["open_discrepancy_count"],
        "total_exposure_ngn": money(r["unreconciled_exposure_ngn"]),
        "status": r["submission_status"],
        "generated_at": r["generated_at"].isoformat(),
    }


@router.get("/daily", dependencies=[Depends(require_role(READ_ROLES))])
async def list_daily_reports(
    limit: int = Query(default=30, ge=1, le=90),
    offset: int = Query(default=0, ge=0),
) -> dict[str, Any]:
    """Most recent daily returns, newest first."""
    async with readonly_session() as session:
        rows = (
            (
                await session.execute(
                    text(_SELECT + " ORDER BY return_date DESC LIMIT :limit OFFSET :offset"),
                    {"limit": limit, "offset": offset},
                )
            )
            .mappings()
            .all()
        )
    reports = [_serialise(r) for r in rows]
    return {"reports": reports, "count": len(reports)}


@router.get("/daily/{report_date}", dependencies=[Depends(require_role(READ_ROLES))])
async def get_daily_report(report_date: date) -> dict[str, Any]:
    async with readonly_session() as session:
        row = (
            (
                await session.execute(
                    text(_SELECT + " WHERE return_date = :d"),
                    {"d": report_date},
                )
            )
            .mappings()
            .first()
        )
    if row is None:
        raise HTTPException(status_code=404, detail=f"No daily return for {report_date.isoformat()}")
    return _serialise(row)
